[package]
name = "server"
version = "0.1.0"
authors = ["tech-cobber <tech-cobber@yandex.ru>"]
edition = "2018"

[dependencies]
image = "0.22.2"
actix-web = "1.0"
serde = "1.0.100"
serde_derive = "1.0.100"
futures = "0.1.29"
